/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as MapRouteImport } from './routes/map'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SosRouteImport } from './routes/sos'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as SheltersIndexRouteImport } from './routes/shelters.index'
import { Route as SheltersShelterIdRouteImport } from './routes/shelters.$shelterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const SheltersIndexRoute = SheltersIndexRouteImport.update({
  id: '/shelters/',
  path: '/shelters/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheltersShelterIdRoute = SheltersShelterIdRouteImport.update({
  id: '/shelters/$shelterId',
  path: '/shelters/$shelterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/donate': typeof DonateRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sos': typeof SosRoute
  '/volunteer': typeof VolunteerRoute
  '/shelters/$shelterId': typeof SheltersShelterIdRoute
  '/shelters/': typeof SheltersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/donate': typeof DonateRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sos': typeof SosRoute
  '/volunteer': typeof VolunteerRoute
  '/shelters/$shelterId': typeof SheltersShelterIdRoute
  '/shelters': typeof SheltersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/donate': typeof DonateRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sos': typeof SosRoute
  '/volunteer': typeof VolunteerRoute
  '/shelters/$shelterId': typeof SheltersShelterIdRoute
  '/shelters/': typeof SheltersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/donate'
    | '/map'
    | '/onboarding'
    | '/permissions'
    | '/profile'
    | '/services'
    | '/sos'
    | '/volunteer'
    | '/shelters/$shelterId'
    | '/shelters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/donate'
    | '/map'
    | '/onboarding'
    | '/permissions'
    | '/profile'
    | '/services'
    | '/sos'
    | '/volunteer'
    | '/shelters/$shelterId'
    | '/shelters'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/donate'
    | '/map'
    | '/onboarding'
    | '/permissions'
    | '/profile'
    | '/services'
    | '/sos'
    | '/volunteer'
    | '/shelters/$shelterId'
    | '/shelters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DonateRoute: typeof DonateRoute
  MapRoute: typeof MapRoute
  OnboardingRoute: typeof OnboardingRoute
  PermissionsRoute: typeof PermissionsRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  SosRoute: typeof SosRoute
  VolunteerRoute: typeof VolunteerRoute
  SheltersShelterIdRoute: typeof SheltersShelterIdRoute
  SheltersIndexRoute: typeof SheltersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelters/': {
      id: '/shelters/'
      path: '/shelters'
      fullPath: '/shelters/'
      preLoaderRoute: typeof SheltersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelters/$shelterId': {
      id: '/shelters/$shelterId'
      path: '/shelters/$shelterId'
      fullPath: '/shelters/$shelterId'
      preLoaderRoute: typeof SheltersShelterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DonateRoute: DonateRoute,
  MapRoute: MapRoute,
  OnboardingRoute: OnboardingRoute,
  PermissionsRoute: PermissionsRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  SosRoute: SosRoute,
  VolunteerRoute: VolunteerRoute,
  SheltersShelterIdRoute: SheltersShelterIdRoute,
  SheltersIndexRoute: SheltersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
